package com.example.financeapp.enums

enum class Currency(val code: String, val displayName: String, val symbol: String) {
    ALL("ALL", "Albania Lek", "L"),
    AFN("AFN", "Afghanistan Afghani", "؋"),
    ARS("ARS", "Argentina Peso", "$"),
    AWG("AWG", "Aruba Guilder", "ƒ"),
    AUD("AUD", "Australia Dollar", "$"),
    AZN("AZN", "Azerbaijan New Manat", "₼"),
    BSD("BSD", "Bahamas Dollar", "$"),
    BBD("BBD", "Barbados Dollar", "$"),
    BYR("BYR", "Belarus Ruble", "Br"),
    BZD("BZD", "Belize Dollar", "BZ$"),
    BMD("BMD", "Bermuda Dollar", "$"),
    BOB("BOB", "Bolivia Boliviano", "Bs."),
    BAM("BAM", "Bosnia and Herzegovina Convertible Marka", "KM"),
    BWP("BWP", "Botswana Pula", "P"),
    BGN("BGN", "Bulgaria Lev", "лв"),
    BRL("BRL", "Brazil Real", "R$"),
    BND("BND", "Brunei Darussalam Dollar", "$"),
    KHR("KHR", "Cambodia Riel", "៛"),
    CAD("CAD", "Canada Dollar", "$"),
    KYD("KYD", "Cayman Islands Dollar", "$"),
    CLP("CLP", "Chile Peso", "$"),
    CNY("CNY", "China Yuan Renminbi", "¥"),
    COP("COP", "Colombia Peso", "$"),
    CRC("CRC", "Costa Rica Colon", "₡"),
    HRK("HRK", "Croatia Kuna", "kn"),
    CUP("CUP", "Cuba Peso", "$"),
    CZK("CZK", "Czech Republic Koruna", "Kč"),
    DKK("DKK", "Denmark Krone", "kr"),
    DOP("DOP", "Dominican Republic Peso", "$"),
    XCD("XCD", "East Caribbean Dollar", "$"),
    EGP("EGP", "Egypt Pound", "£"),
    SVC("SVC", "El Salvador Colon", "$"),
    EEK("EEK", "Estonia Kroon", "KR"),
    EUR("EUR", "Euro Member Countries", "€"),
    FKP("FKP", "Falkland Islands (Malvinas) Pound", "£"),
    FJD("FJD", "Fiji Dollar", "$"),
    GHC("GHC", "Ghana Cedis", "¢"),
    GIP("GIP", "Gibraltar Pound", "£"),
    GTQ("GTQ", "Guatemala Quetzal", "Q"),
    GGP("GGP", "Guernsey Pound", "£"),
    GYD("GYD", "Guyana Dollar", "$"),
    HNL("HNL", "Honduras Lempira", "L"),
    HKD("HKD", "Hong Kong Dollar", "$"),
    HUF("HUF", "Hungary Forint", "Ft"),
    ISK("ISK", "Iceland Krona", "kr"),
    INR("INR", "India Rupee", "₹"),
    IDR("IDR", "Indonesia Rupiah", "Rp"),
    IRR("IRR", "Iran Rial", "﷼"),
    IMP("IMP", "Isle of Man Pound", "£"),
    ILS("ILS", "Israel Shekel", "₪"),
    JMD("JMD", "Jamaica Dollar", "J$"),
    JPY("JPY", "Japan Yen", "¥"),
    JEP("JEP", "Jersey Pound", "£"),
    KZT("KZT", "Kazakhstan Tenge", "лв"),
    KPW("KPW", "Korea (North) Won", "₩"),
    KRW("KRW", "Korea (South) Won", "₩"),
    KGS("KGS", "Kyrgyzstan Som", "лв"),
    LAK("LAK", "Laos Kip", "₭"),
    LVL("LVL", "Latvia Lat", "Ls"),
    LBP("LBP", "Lebanon Pound", "£"),
    LRD("LRD", "Liberia Dollar", "$"),
    LTL("LTL", "Lithuania Litas", "Lt"),
    MKD("MKD", "Macedonia Denar", "ден"),
    MYR("MYR", "Malaysia Ringgit", "RM"),
    MUR("MUR", "Mauritius Rupee", "₨"),
    MXN("MXN", "Mexico Peso", "$"),
    MNT("MNT", "Mongolia Tughrik", "₮"),
    MZN("MZN", "Mozambique Metical", "MT"),
    NAD("NAD", "Namibia Dollar", "$"),
    NPR("NPR", "Nepal Rupee", "₨"),
    ANG("ANG", "Netherlands Antilles Guilder", "ƒ"),
    NZD("NZD", "New Zealand Dollar", "$"),
    NIO("NIO", "Nicaragua Cordoba", "C$"),
    NGN("NGN", "Nigeria Naira", "₦"),
    NOK("NOK", "Norway Krone", "kr"),
    OMR("OMR", "Oman Rial", "﷼"),
    PKR("PKR", "Pakistan Rupee", "₨"),
    PAB("PAB", "Panama Balboa", "B/."),
    PYG("PYG", "Paraguay Guarani", "Gs"),
    PEN("PEN", "Peru Nuevo Sol", "S/."),
    PHP("PHP", "Philippines Peso", "₱"),
    PLN("PLN", "Poland Zloty", "zł"),
    QAR("QAR", "Qatar Riyal", "﷼"),
    RON("RON", "Romania New Leu", "lei"),
    RUB("RUB", "Russia Ruble", "₽"),
    SHP("SHP", "Saint Helena Pound", "£"),
    SAR("SAR", "Saudi Arabia Riyal", "﷼"),
    RSD("RSD", "Serbia Dinar", "Дин."),
    SCR("SCR", "Seychelles Rupee", "₨"),
    SGD("SGD", "Singapore Dollar", "$"),
    SBD("SBD", "Solomon Islands Dollar", "$"),
    SOS("SOS", "Somalia Shilling", "S"),
    ZAR("ZAR", "South Africa Rand", "R"),
    KRW2("KRW", "Korea (South) Won", "₩"), // Duplicate code for South Korea Won
    LKR("LKR", "Sri Lanka Rupee", "₨"),
    SEK("SEK", "Sweden Krona", "kr"),
    CHF("CHF", "Switzerland Franc", "CHF"),
    SRD("SRD", "Suriname Dollar", "$"),
    SYP("SYP", "Syria Pound", "£"),
    TWD("TWD", "Taiwan New Dollar", "NT$"),
    THB("THB", "Thailand Baht", "฿"),
    TTD("TTD", "Trinidad and Tobago Dollar", "TT$"),
    TRY("TRY", "Turkey Lira", "₺"),
    TVD("TVD", "Tuvalu Dollar", "$"),
    UAH("UAH", "Ukraine Hryvna", "₴"),
    GBP("GBP", "United Kingdom Pound", "£"),
    USD("USD", "United States Dollar", "$"),
    UYU("UYU", "Uruguay Peso", "\$U"),
    UZS("UZS", "Uzbekistan Som", "лв"),
    VEF("VEF", "Venezuela Bolivar", "Bs"),
    VND("VND", "Viet Nam Dong", "₫"),
    YER("YER", "Yemen Rial", "﷼"),
    ZWD("ZWD", "Zimbabwe Dollar", "Z$");

    companion object {
        fun fromCode(code: String): Currency? {
            return values().find { it.code == code }
        }
    }
}
