package com.example.financeapp.enums

enum class Currency(val code: String, val displayName: String, val symbol: String) {
    AED("AED", "United Arab Emirates Dirham", "د.إ"),
    AFN("AFN", "Afghan Afghani", "؋"),
    ALL("ALL", "Albanian Lek", "L"),
    AMD("AMD", "Armenian Dram", "֏"),
    ANG("ANG", "Netherlands Antillean Guilder", "ƒ"),
    AOA("AOA", "Angolan Kwanza", "Kz"),
    ARS("ARS", "Argentine Peso", "$"),
    AUD("AUD", "Australian Dollar", "$"),
    AWG("AWG", "Aruban Florin", "ƒ"),
    AZN("AZN", "Azerbaijani Manat", "₼"),
    BAM("BAM", "Bosnia-Herzegovina Convertible Mark", "KM"),
    BBD("BBD", "Barbadian Dollar", "$"),
    BDT("BDT", "Bangladeshi Taka", "৳"),
    BGN("BGN", "Bulgarian Lev", "лв"),
    BHD("BHD", "Bahraini Dinar", "ب.د"),
    BIF("BIF", "Burundian Franc", "FBu"),
    BMD("BMD", "Bermudian Dollar", "$"),
    BND("BND", "Brunei Dollar", "$"),
    BOB("BOB", "Bolivian Boliviano", "Bs."),
    BRL("BRL", "Brazilian Real", "R$"),
    BSD("BSD", "Bahamian Dollar", "$"),
    BTC("BTC", "Bitcoin", "₿"),
    BTN("BTN", "Bhutanese Ngultrum", "Nu."),
    BWP("BWP", "Botswana Pula", "P"),
    BYN("BYN", "Belarusian Ruble", "Br"),
    BYR("BYR", "Belarusian Ruble (old)", "Br"),
    BZD("BZD", "Belize Dollar", "BZ$"),
    CAD("CAD", "Canadian Dollar", "$"),
    CDF("CDF", "Congolese Franc", "FC"),
    CHF("CHF", "Swiss Franc", "CHF"),
    CLF("CLF", "Chilean Unit of Account (UF)", "UF"),
    CLP("CLP", "Chilean Peso", "$"),
    CNY("CNY", "Chinese Yuan", "¥"),
    COP("COP", "Colombian Peso", "$"),
    CRC("CRC", "Costa Rican Colón", "₡"),
    CUC("CUC", "Cuban Convertible Peso", "CUC"),
    CUP("CUP", "Cuban Peso", "$"),
    CVE("CVE", "Cape Verdean Escudo", "$"),
    CZK("CZK", "Czech Koruna", "Kč"),
    DJF("DJF", "Djiboutian Franc", "Fdj"),
    DKK("DKK", "Danish Krone", "kr"),
    DOP("DOP", "Dominican Peso", "RD$"),
    DZD("DZD", "Algerian Dinar", "د.ج"),
    EGP("EGP", "Egyptian Pound", "£"),
    ERN("ERN", "Eritrean Nakfa", "Nfk"),
    ETB("ETB", "Ethiopian Birr", "Br"),
    EUR("EUR", "Euro", "€"),
    FJD("FJD", "Fijian Dollar", "FJ$"),
    FKP("FKP", "Falkland Islands Pound", "£"),
    GBP("GBP", "British Pound Sterling", "£"),
    GEL("GEL", "Georgian Lari", "₾"),
    GGP("GGP", "Guernsey Pound", "£"),
    GHS("GHS", "Ghanaian Cedi", "GH₵"),
    GIP("GIP", "Gibraltar Pound", "£"),
    GMD("GMD", "Gambian Dalasi", "D"),
    GNF("GNF", "Guinean Franc", "FG"),
    GTQ("GTQ", "Guatemalan Quetzal", "Q"),
    GYD("GYD", "Guyanaese Dollar", "$"),
    HKD("HKD", "Hong Kong Dollar", "$"),
    HNL("HNL", "Honduran Lempira", "L"),
    HRK("HRK", "Croatian Kuna", "kn"),
    HTG("HTG", "Haitian Gourde", "G"),
    HUF("HUF", "Hungarian Forint", "Ft"),
    IDR("IDR", "Indonesian Rupiah", "Rp"),
    ILS("ILS", "Israeli New Sheqel", "₪"),
    IMP("IMP", "Isle of Man Pound", "£"),
    INR("INR", "Indian Rupee", "₹"),
    IQD("IQD", "Iraqi Dinar", "ع.د"),
    IRR("IRR", "Iranian Rial", "﷼"),
    ISK("ISK", "Icelandic Króna", "kr"),
    JEP("JEP", "Jersey Pound", "£"),
    JMD("JMD", "Jamaican Dollar", "J$"),
    JOD("JOD", "Jordanian Dinar", "د.ا"),
    JPY("JPY", "Japanese Yen", "¥"),
    KES("KES", "Kenyan Shilling", "KSh"),
    KGS("KGS", "Kyrgyzstani Som", "с"),
    KHR("KHR", "Cambodian Riel", "៛"),
    KMF("KMF", "Comorian Franc", "CF"),
    KPW("KPW", "North Korean Won", "₩"),
    KRW("KRW", "South Korean Won", "₩"),
    KWD("KWD", "Kuwaiti Dinar", "د.ك"),
    KYD("KYD", "Cayman Islands Dollar", "$"),
    KZT("KZT", "Kazakhstani Tenge", "₸"),
    LAK("LAK", "Laotian Kip", "₭"),
    LBP("LBP", "Lebanese Pound", "ل.ل"),
    LKR("LKR", "Sri Lankan Rupee", "රු"),
    LRD("LRD", "Liberian Dollar", "$"),
    LSL("LSL", "Lesotho Loti", "L"),
    LVL("LVL", "Latvian Lats", "Ls"),
    LYD("LYD", "Libyan Dinar", "ل.د"),
    MAD("MAD", "Moroccan Dirham", "MAD"),
    MDL("MDL", "Moldovan Leu", "lei"),
    MGA("MGA", "Malagasy Ariary", "Ar"),
    MKD("MKD", "Macedonian Denar", "ден"),
    MMK("MMK", "Myanmar Kyat", "K"),
    MNT("MNT", "Mongolian Tugrik", "₮"),
    MOP("MOP", "Macanese Pataca", "MOP$"),
    MRO("MRO", "Mauritanian Ouguiya", "UM"),
    MUR("MUR", "Mauritian Rupee", "₨"),
    MVR("MVR", "Maldivian Rufiyaa", "Rf"),
    MWK("MWK", "Malawian Kwacha", "MK"),
    MXN("MXN", "Mexican Peso", "$"),
    MYR("MYR", "Malaysian Ringgit", "RM"),
    MZN("MZN", "Mozambican Metical", "MT"),
    NAD("NAD", "Namibian Dollar", "$"),
    NGN("NGN", "Nigerian Naira", "₦"),
    NIO("NIO", "Nicaraguan Córdoba", "C$"),
    NOK("NOK", "Norwegian Krone", "kr"),
    NPR("NPR", "Nepalese Rupee", "₨"),
    NZD("NZD", "New Zealand Dollar", "$"),
    OMR("OMR", "Omani Rial", "ر.ع."),
    PAB("PAB", "Panamanian Balboa", "B/."),
    PEN("PEN", "Peruvian Nuevo Sol", "S/."),
    PGK("PGK", "Papua New Guinean Kina", "K"),
    PHP("PHP", "Philippine Peso", "₱"),
    PKR("PKR", "Pakistani Rupee", "₨"),
    PLN("PLN", "Polish Zloty", "zł"),
    PYG("PYG", "Paraguayan Guarani", "₲"),
    QAR("QAR", "Qatari Rial", "ر.ق"),
    RON("RON", "Romanian Leu", "lei"),
    RSD("RSD", "Serbian Dinar", "дин."),
    RUB("RUB", "Russian Ruble", "₽"),
    RWF("RWF", "Rwandan Franc", "RF"),
    SAR("SAR", "Saudi Riyal", "ر.س"),
    SBD("SBD", "Solomon Islands Dollar", "SI$"),
    SCR("SCR", "Seychellois Rupee", "₨"),
    SDG("SDG", "Sudanese Pound", "ج.س."),
    SEK("SEK", "Swedish Krona", "kr"),
    SGD("SGD", "Singapore Dollar", "$"),
    SHP("SHP", "Saint Helenian Pound", "£"),
    SLL("SLL", "Sierra Leonean Leone", "Le"),
    SOS("SOS", "Somali Shilling", "Sh"),
    SPL("SPL", "Seborgan Luigino", ""),
    SRD("SRD", "Surinamese Dollar", "$"),
    STD("STD", "São Tomé and Príncipe Dobra", "Db"),
    SVC("SVC", "Salvadoran Colón", "$"),
    SYP("SYP", "Syrian Pound", "£"),
    SZL("SZL", "Swazi Lilangeni", "E"),
    THB("THB", "Thai Baht", "฿"),
    TJS("TJS", "Tajikistani Somoni", "SM"),
    TMT("TMT", "Turkmenistani Manat", "T"),
    TND("TND", "Tunisian Dinar", "د.ت"),
    TOP("TOP", "Tongan Pa'anga", "T$"),
    TRY("TRY", "Turkish Lira", "₺"),
    TTD("TTD", "Trinidad and Tobago Dollar", "TT$"),
    TVD("TVD", "Tuvaluan Dollar", "$"),
    TWD("TWD", "New Taiwan Dollar", "NT$"),
    TZS("TZS", "Tanzanian Shilling", "TSh"),
    UAH("UAH", "Ukrainian Hryvnia", "₴"),
    UGX("UGX", "Ugandan Shilling", "USh"),
    USD("USD", "United States Dollar", "$"),
    UYU("UYU", "Uruguayan Peso", "\$U"),
    UZS("UZS", "Uzbekistan Som", "лв"),
    VEF("VEF", "Venezuelan Bolívar Fuerte", "Bs"),
    VND("VND", "Vietnamese Dong", "₫"),
    VUV("VUV", "Vanuatu Vatu", "VT"),
    WST("WST", "Samoan Tala", "WS$"),
    XAF("XAF", "CFA Franc BEAC", "FCFA"),
    XAG("XAG", "Silver (troy ounce)", "oz t"),
    XCD("XCD", "East Caribbean Dollar", "$"),
    XDR("XDR", "Special Drawing Rights", "SDR"),
    XOF("XOF", "CFA Franc BCEAO", "CFA"),
    XPF("XPF", "CFP Franc", "₣"),
    YER("YER", "Yemeni Rial", "﷼"),
    ZAR("ZAR", "South African Rand", "R"),
    ZMK("ZMK", "Old Zambian Kwacha", "ZK"),
    ZMW("ZMW", "Zambian Kwacha", "ZK"),
    ZWL("ZWL", "Zimbabwean Dollar", "Z$");

    companion object {
        fun fromCode(code: String): Currency? {
            return values().find { it.code == code }
        }
    }
}
